### ISSUE TITLE
Shortcut Button View Controller not working

### ISSUE THREAD

**Issue by Kaven01** [Adonit/LAMY-iPadOS-SDK#2]
I am using this SDK on iPad, and I have a possible issue with Shortcut Button View Controller ( LamyViewControllerShortCutsIdentifier ). 

When viewed, controller shows a LAMY stylus image on top, and list of my predefined shortcuts below it. I can tap on list items, and they become checked. However

1) I don't see any way of how to choose what button I want to set shortcut to. Stylus image in uninteractive, and I don't see ani blue circle around stylus button as in image here: https://github.com/Adonit/LAMY-iPadOS-SDK/wiki/Shortcut-Button-View-Controller  . I did not find any way of saying "now I want to set shortcut for button 2".

2) Even if I choose a shortcut and it becomes checked, it does not set it to any button. I am able to set shortcuts by `manager?.addShortcutOptionButton1Default(shortcut)` (which works), but not visually by Shortcut Button View Controller

3) Moreover, if I check a shortcut in Shortcut Button View Controller and then close the view and open it again, shortcut is no longer shown as checked. Generally, it seems that chosing predefined shortcuts in Shortcut Button View Controller does nothing, and the choice is not remembered anywhere.

**Comment by adonitDevel** [comment]
Hi @Kaven01 , 
I make some code changes to fix this issue. 
Please try SDK 1.0.3, and I update the example(swift version) for your reference.
https://raw.githubusercontent.com/Adonit/LAMY-iPadOS-SDK/V1.0.3/LamySafariNoteplusExample-Swift/LamySafariNoteplusExample-Swift/ViewController.swift

Sorry for your inconvenience.

**Comment by Kaven01** [comment]
I believe there is still some bug there. The views are certainly working and are successfully assigning shortcuts to buttons, but there seems to be no difference between LamyViewControllerShortCutButtonAIdentifier and LamyViewControllerShortCutButtonBIdentifier . Both are showing the same stylus image (with circle around lower button), and both are assigning shortcuts to the same stylus button (again the lower one). None allows me to assign shortcut to the upper stylus button.

**Comment by adonitDevel** [comment]
Hi @Kaven01,
Sorry my mistake. 
I fixed it in SDK(1.0.4).  
Please see the picture below,  
<img src="https://github.com/Adonit/LAMY-iPadOS-SDK/assets/5852949/59217b35-c94b-4185-b105-7345b9161b3b" width=35% height=40%><img src="https://github.com/Adonit/LAMY-iPadOS-SDK/assets/5852949/7a3e1147-bebd-41c5-911e-9f79f935960b" width=35% height=40%>

**Comment by Kaven01** [comment]
Yeah, that's better :-) It works now. 
I have however run into another problem, assigned shortcuts sometimes stop to be called. I am creating a new issue for it.
